### ISSUE TITLE
搭建开发环境注意事项

### ISSUE THREAD

**Issue by Jason-mor** [Jason-mor/learn#2]
##### 安装git和tortoiseGit

http://www.jb51.net/article/55440.htm
##### eclipse插件easyexplore

http://blog.csdn.net/leilu2008/article/details/8229053
##### 升级jdk1.7，最好首先卸载jdk1.6，可恶的360

http://jingyan.baidu.com/article/c843ea0b755c7977931e4ab1.html
##### 文本编辑器

https://atom.io/
editplus
##### eclipse版本 vs jdk版本

http://blog.csdn.net/zyz511919766/article/details/7442633

**Comment by Jason-mor** [comment]
之前碰到tortoiseGit无法pull和push代码的问题。
搜索资料原因是安装过程中需要选择OPenssh

**Comment by Jason-mor** [comment]
要么捆绑百度杀毒，360捆绑一坨。安装软件，不要找它们推荐的，会有很多没有的东西跟着。还是自己找绿色版，好

**Comment by Jason-mor** [comment]
sublime 2.0.2 注册码
http://blog.csdn.net/wolf199103/article/details/17999425

**Comment by Jason-mor** [comment]
1 tomcat和jdk配置
http://jingyan.baidu.com/article/86f4a73e5be03237d65269ef.html

2 git安装

http://www.jb51.net/article/55438.htm

**Comment by Ericma1988** [comment]
fastStone
http://www.ihacksoft.com/faststone-capture-7-6.html

**Comment by Jason-mor** [comment]
git 命令
git branch -va
git checkout -t origin/dev
