### ISSUE TITLE
晨读

### ISSUE THREAD

**Issue by Jason-mor** [Jason-mor/learn#39]
早上看书记录，时间长了，就不那么容易想起来看了什么。

好记性不如记录

**Comment by Jason-mor** [comment]
20160311

预先加载，合并请求，缩小数据，提升性能。
http://hectorguo.com/zh/http2-starter/

http://www.barretlee.com/blog/2016/02/16/when-fe-has-the-power-of-server/
严格模式
http://www.html-js.com/article/3443
http://www.infoq.com/cn/articles/how-html5-achieve-native-performance

**Comment by Jason-mor** [comment]
20160314

web缓存
http://www.alloyteam.com/2016/03/discussion-on-web-caching/

渐变  css
http://www.alloyteam.com/2016/03/css-gradient/

**Comment by Jason-mor** [comment]
20160315

http://www.zcfy.cc/article/171
node的全局安装

http://taobaofed.org/blog/2016/03/11/react-web-intro/
react native运行在web客户端函数式

函数式语言副作用
http://www.w3ctech.com/topic/1718

**Comment by Jason-mor** [comment]
20160316

http://reactjs.cn/react/docs/jsx-spread.html
react. 的jsx相关语法

**Comment by Jason-mor** [comment]
20160317
延伸属性
http://reactjs.cn/react/docs/jsx-spread.html
自定义html属性
http://reactjs.cn/react/docs/jsx-gotchas.html

state如何使用
http://reactjs.cn/react/docs/interactivity-and-dynamic-uis.html
组合性能，key类似track by
http://reactjs.cn/react/docs/multiple-components.html

**Comment by Jason-mor** [comment]
20160318

受限组件和非受限组件
http://reactjs.cn/react/docs/forms.html

浏览器相关，兼容低版本ie
http://reactjs.cn/react/docs/working-with-the-browser.html

**Comment by Jason-mor** [comment]
20160319
ref的使用
http://reactjs.cn/react/docs/more-about-refs.html

jsx的使用，不要在客户端浪费性能
http://reactjs.cn/react/docs/tooling-integration.html

fidder使用
http://www.cnblogs.com/jifeng/p/4500816.html

**Comment by Jason-mor** [comment]
20160321

react插件
http://reactjs.cn/react/docs/pure-render-mixin.html

写本地测试用例，增加requirejs配置，试用requirejs。

**Comment by Jason-mor** [comment]
20160324
前端技术栈
http://pinggod.com/2016/2016-JavaScript-%E6%8A%80%E6%9C%AF%E6%A0%88%E5%B1%95%E6%9C%9B/

前端性能优化 
http://aotu.io/notes/2016/03/16/optimization/

**Comment by Jason-mor** [comment]
20160325
http://kazzkiq.github.io/balloon.css/
系统自动启动
http://www.ruanyifeng.com/blog/2016/03/node-systemd-tutorial.html

视频相关
http://yanhaijing.com/html/2016/03/12/html5-video/

http://aotu.io/notes/2016/03/17/http2-char/

**Comment by Jason-mor** [comment]
20160326

闭包
http://zhuanlan.zhihu.com/browsnet/20658538
xframe通过iframe的安全漏洞
https://www.zhuyingda.com/blog/b6.html?origin=75

**Comment by Jason-mor** [comment]
20160328

前端迷你库
http://yanhaijing.com/javascript/2015/12/29/mini-js-lib/

**Comment by Jason-mor** [comment]
20160330

jquery
缓存机制  回溯机制，提高性能

**Comment by Jason-mor** [comment]
20160405
decroator
http://blog.h5jun.com/post/decorator-functional.html
css相关内容
http://www.w3ctech.com/topic/1735

**Comment by Jason-mor** [comment]
20160407

angular2的快速入门，说实话看了一遍没有什么感觉。angular2迟迟没有发布正式版，可能考虑到大众用户的接受程度，与typescript的半强相关绑定，可能有增加了学习typescript的成本

angukar1推出获得巨大成功之后，很多框架看到了它的不足，将类似样检测的能力优化，并且支持低版本的ie，比如尤大神的vue，司徒的avalon都是很好的例子

去年facebook非常成功的react,无疑给angular2又增加了一个强大的竞争对手。性能和浏览器支持比angular1强大很多

mark一下，看google团队会推出什么样惊艳的全新框架与react一绝高下。还有其他前端框架的竞争

https://segmentfault.com/a/1190000004517842

**Comment by Jason-mor** [comment]
20160408

http://m.w2bc.com/article/50764

http://www.alloyteam.com/2016/03/master-npm/

webpack  npm3

**Comment by Jason-mor** [comment]
20160411

http://qianduan.guru/2016/04/04/npm-left-pad-have-we-forgotten-how-to-program/
leftpad事件延续
http://taobaofed.org/blog/2016/04/01/lose-statistics/
日志跟踪
http://www.jianshu.com/p/84b75e1c0bd4
vr3d

**Comment by Jason-mor** [comment]
20160412
http://www.zhangxinxu.com/wordpress/2016/04/know-about-html-download-attribute/
html的download属性
http://zhuanlan.zhihu.com/p/20707030
css相关讨论
fido联盟介绍
http://www.zcfy.cc/article/189

**Comment by Jason-mor** [comment]
20160413

淘宝首页性能优化
http://taobaofed.org/blog/2016/04/05/optimize-in-tbhome/
gulp
http://blog.h5jun.com/post/gulp-build.html
原型继承与类继承
http://blog.h5jun.com/post/inherits.html

**Comment by Jason-mor** [comment]
20160414

http://taobaofed.org/blog/2015/11/09/web-performance/

淘宝首页性能

http://taobaofed.org/blog/2015/12/07/some-thing-about-random/
没有很看懂

**Comment by Ericma1988** [comment]
chrome渲染性能相关
https://developers.google.com/web/fundamentals/performance/rendering/

**Comment by Jason-mor** [comment]
20150419

阮一峰  同源策略
http://www.ruanyifeng.com/blog/2016/04/same-origin-policy.html

**Comment by Jason-mor** [comment]
20160420

base64编码
http://my.oschina.net/goal/blog/201032

**Comment by Jason-mor** [comment]
20160421

es6
https://blog.oyanglul.us/javascript/essential-ecmascript6.html

**Comment by Jason-mor** [comment]
20160422

promise:
http://mp.weixin.qq.com/s?__biz=MzA4NjE3MDg4OQ==&mid=2650963217&idx=1&sn=242efadbfe1964e9c04865ba32356afb&scene=0#wechat_redirect

javascript是否有值
http://m.blog.csdn.net/article/details?id=51136511

编译模板引引擎
http://blog.jobbole.com/56689/

**Comment by Jason-mor** [comment]
20160423

javascript操作硬件，靠谱吗？是广告吗
http://mp.weixin.qq.com/s?__biz=MzI4NjA2MTQwNQ==&mid=2247483666&idx=1&sn=55a7d60c1ece260bbe6fc27e5665c278&scene=1&srcid=0422xkGbzzyuTvADbWoP2nzI&from=groupmessage&isappinstalled=0#wechat_redirect

对css的background的使用
http://blog.doyoe.com/2016/04/11/css/background%E7%B3%BB%E5%88%97%E4%B9%8B%E6%97%A0%E5%A4%84%E4%B8%8D%E5%9C%A8%E7%9A%84%E5%A6%99%E8%B6%A3/

**Comment by Jason-mor** [comment]
20160425

靠谱的javascript程序员
http://ourjs.com/detail/52b0fb82d6feceaa0400000b

**Comment by Jason-mor** [comment]
20160428

ecma继承机制
http://www.w3school.com.cn/js/pro_js_inheritance_implementing.asp
继承方式
http://www.ruanyifeng.com/blog/2010/05/object-oriented_javascript_inheritance.html
struts2漏洞
http://mp.weixin.qq.com/s?__biz=MzIyMjExNzk5NQ==&mid=2653079370&idx=1&sn=dfd50a7a2ad8f61cfb4508fc4f09f3d2&scene=1&srcid=0426kWVf4zNCk1v6lWtrM0vD&from=groupmessage&isappinstalled=0#wechat_redirect

**Comment by Jason-mor** [comment]
20160503

vue2.0
http://jiongks.name/blog/announcing-vue-2/

**Comment by Jason-mor** [comment]
20160504

框架对比
http://www.ibm.com/developerworks/cn/web/1404_wangfx_jsframeworks/

证书相关
http://www.barretlee.com/blog/2016/04/24/detail-about-ca-and-certs/

**Comment by Jason-mor** [comment]
20160509

css如何开启硬件加速，需要测试性能，观察是否可以提高性能，开启gpu,会导致内存增加
http://www.cnblogs.com/PeunZhang/p/3510083.html

**Comment by Jason-mor** [comment]
20260522

bfc相关，产生新的bfc为什么可以闭合浮动

http://m.baidu.com/from=2001a/bd_page_type=1/ssid=0/uid=0/pu=usm%400%2Csz%401320_1003%2Cta%40iphone_2_5.0_1_10.9/baiduid=F333D76A428F9E7B477E8681D2C5E81C/w=0_10_%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BA%A7%E7%94%9F%E6%96%B0%E7%9A%84bfc%2C%E5%8F%AF%E4%BB%A5%E8%A7%A3%E5%86%B3%E9%AB%98%E5%BA%A6%E5%A1%8C%E9%99%B7%E9%97%AE%E9%A2%98/t=iphone/l=3/tc?ref=www_iphone&lid=17502814454270491874&order=1&vit=osres&tj=www_normal_1_0_10_title&m=8&srd=1&cltj=cloud_title&dict=30&nt=wnor&title=%E6%88%91%E5%AF%B9BFC%E7%9A%84%E7%90%86%E8%A7%A3-%E6%9C%A8%E7%9A%84%E6%A0%91-%E5%8D%9A%E5%AE%A2%E5%9B%AD&sec=12429&di=fc4100a4cd9846f3&bdenc=1&tch=124.0.0.0.0.0&nsrc=IlPT2AEptyoA_yixCFOxXnANedT62v3IEQGG_ytK1DK6mlrte4viZQRAZjz-LzKKCVuwdoSOxBt8w87i2mYn7gwTaP1s&eqid=f2e67d03245d8000100000045740d9e4&wd=&clk_info=%7B%22srcid%22%3A%22www_normal%22%2C%22tplname%22%3A%22www_normal%22%2C%22t%22%3A1463867946775%2C%22xpath%22%3A%22div-div-div2-a-p%22%7D

**Comment by Jason-mor** [comment]
20160525

贝塞尔曲线
http://www.w3cplus.com/animation/mathematical-intuition-behind-bezier-curves.html

javascript定时器
http://www.alloyteam.com/2016/05/javascript-timer/

**Comment by Jason-mor** [comment]
20160528

是否应该尽快切换https
https://imququ.com/post/moving-to-https-asap.html
dropshadow
http://www.zhangxinxu.com/wordpress/2016/05/css3-filter-drop-shadow-vs-box-shadow/
开源协议介绍
http://www.ha97.com/833.html

top10单页应用框架
http://www.zcfy.cc/article/272

**Comment by Jason-mor** [comment]
20160528
使用认证管理api登陆
http://www.zcfy.cc/article/224
软件工程师的素质
https://zhuanlan.zhihu.com/p/20824976

angular2快速入门
https://segmentfault.com/a/1190000004517842

web动画，key frames
http://www.w3cplus.com/animation/web-animations-learning-to-love-the-api.html

**Comment by Jason-mor** [comment]
20160530

别人家的面试题，num被4整除
https://www.h5jun.com/post/power-of-four.html

**Comment by Jason-mor** [comment]
20160601

手机视频播放问题
http://taobaofed.org/blog/2016/05/23/video-player/
直接用html5标签可以吗？

**Comment by Jason-mor** [comment]
20160602

开发无障碍web组件
http://www.zcfy.cc/article/320

object-position
http://www.zcfy.cc/article/318

**Comment by Jason-mor** [comment]
后续晨读内容放到每天的日志中，关闭此issue

**Comment by Jason-mor** [comment]
后续晨读内容放到每天的日志中，关闭此issue
